name: .NET 10 CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # ၁။ Code ဆွဲယူမယ်
    - name: Checkout Source Code
      uses: actions/checkout@v4

    # ၂။ .NET SDK သွင်းမယ်
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    # ၃။ Restore လုပ်မယ်
    - name: Restore Dependencies
      run: dotnet restore

    # ၄။ Build လုပ်မယ်
    - name: Build Application
      run: dotnet build --configuration Release --no-restore

    # ၅။ Test ပတ်မယ်
    - name: Run Automated Tests
      run: dotnet test --no-build --verbosity normal

    # ၆။ AWS ပေါ်တင်ဖို့အတွက် Publish လုပ်ပြီး Zip ဖိုင် ထုတ်မယ် (CD ခြေလှမ်းစပြီ)
    #- name: Publish Application Artifact
    #  run: dotnet publish --configuration Release --output ./publish_output
    # ၆။ AWS ပေါ်တင်ဖို့အတွက် Self-Contained ပုံစံနဲ့ Runtime ပါတစ်ခါတည်း ထည့်ထုတ်မယ်
    # (ပြောင်းလဲချက်- --runtime linux-x64 --self-contained true ကို ထည့်လိုက်တာပါ)
    - name: Publish Application Artifact
      run: dotnet publish --configuration Release --output ./publish_output --runtime linux-x64 --self-contained true
      
    # ၇။ ထွက်လာတဲ့ File တွေကို Zip ချုပ်မယ်
    - name: Generate Deployment Package
      run: |
        cd ./publish_output
        zip -r ../deploy-package.zip .
        cd ..

    # ၈။ AWS ပေါ်သို့ အလိုအလျောက် လှမ်းတင်ပြီ! (The Magic Step)
    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: 'my_test_web_api' # ခင်ဗျား AWS မှာ ပေးခဲ့တဲ့ App Name
        environment_name: 'Mytestwebapi-env' # AWS က အလိုအလျောက် ပေးလိုက်တဲ့ Environment Name (AWS မှာ ပြန်ကြည့်ပါ)
        version_label: 'build-${{ github.run_number }}'
        region: 'ap-southeast-1' # ခင်ဗျား သုံးထားတဲ့ AWS Region (ဥပမာ- us-east-1 သို့မဟုတ် ap-southeast-1)
        deployment_package: 'deploy-package.zip'